apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pms-crossref.fullname" . }}-config
  labels:
    {{- include "pms-crossref.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      profiles:
        active: k8s