spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pms-db
    username: pms-usr
    password: pms-pw
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

logging:
  level:
    com.pms.crossref: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG