spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-instance-pms.cvk4yqey0ex7.us-east-2.rds.amazonaws.com:5432/pms_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:PMS.2025}
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

logging:
  level:
    com.pms.crossref: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG